-- THIS SCRIPT WILL COPY THE GENERATED DDL IN THE APPLICATION
-- AND CREATE ACTUAL OBJECTS IN YOUR TARGET DATABASE.  YOU HAVE
-- TO DO THIS OUTSIDE THE APP SO THAT GRANTS ARE NOT NEEDED
-- FOR THE APP AND YOU CAN SEE EVERYTHING THAT IS EXECUTED IN
-- THE LOG.   
--
-- REPLACE MIGRATESQLAPP WITH THE NAME OF THE APP IN YOUR ENVIRONMENT
--
-- THIS HAS TO BE DONE BECAUSE SNOWFLAKE SECURITY WONT LET YOU
-- GENERATE THE DDL FOR THE OBJECTS CURRENTLY IN THE APP

DECLARE

    SCHEMA_CURSOR CURSOR FOR SELECT X.SCHEMA_DDL, 
          FROM MIGRATESQLAPP._METADATA.MSSQL_SCHEMAS X;

    TABLE_CURSOR CURSOR FOR SELECT X.TABLE_DDL
          FROM MIGRATESQLAPP._METADATA.MSSQL_TABLES X;

    VIEW_CURSOR CURSOR FOR SELECT X.VIEW_DDL
          FROM MIGRATESQLAPP._METADATA.MSSQL_VIEWS X;

    FOREIGN_KEY_CURSOR CURSOR FOR SELECT X.FOREIGN_KEY_DDL
          FROM MIGRATESQLAPP._METADATA.MSSQL_FOREIGN_KEYS X;

    DDL STRING;

BEGIN

    OPEN SCHEMA_CURSOR;

    FOR _SCHEMA_RECORD IN SCHEMA_CURSOR DO

        DDL := _SCHEMA_RECORD.SCHEMA_DDL;

        EXECUTE IMMEDIATE :DDL;

    END FOR;

    CLOSE SCHEMA_CURSOR;


    OPEN TABLE_CURSOR;

    FOR _TABLE_RECORD IN TABLE_CURSOR DO

        DDL := _TABLE_RECORD.TABLE_DDL;

        EXECUTE IMMEDIATE :DDL;

    END FOR;

    CLOSE TABLE_CURSOR;

    OPEN VIEW_CURSOR;

    FOR _VIEW_RECORD IN VIEW_CURSOR DO

        DDL := _VIEW_RECORD.VIEW_DDL;

        EXECUTE IMMEDIATE :DDL;

    END FOR;

    CLOSE VIEW_CURSOR;

    OPEN FOREIGN_KEY_CURSOR;

    FOR _FOREIGN_KEY_RECORD IN FOREIGN_KEY_CURSOR DO

        DDL := _FOREIGN_KEY_RECORD.VIEW_DDL;

        EXECUTE IMMEDIATE :DDL;

    END FOR;

    CLOSE FOREIGN_KEY_CURSOR;


    RETURN 'SCHEMA OBJECTS CREATED';
      
END;
