-- THIS SCRIPT WILL COPY THE GENERATED DDL IN THE APPLICATION
-- AND CREATE ACTUAL OBJECTS IN YOUR TARGET DATABASE.  YOU HAVE
-- TO DO THIS OUTSIDE THE APP SO THAT GRANTS ARE NOT NEEDED
-- FOR THE APP AND YOU CAN SEE EVERYTHING THAT IS EXECUTED IN
-- THE LOG.   
--
-- THIS HAS TO BE DONE BECAUSE SNOWFLAKE SECURITY WONT LET YOU
-- GENERATE THE DDL FOR THE OBJECTS CURRENTLY IN THE APP

USE DATABASE <<ENTER_APPLICATION_DATABASE_NAME>>;
USE SCHEMA _METADATA;

DECLARE

    TARGET_DATABASE_NAME STRING DEFAULT '<<ENTER_TARGET_DATABASE_NAME>>';
    
    METADATA_ID INTEGER DEFAULT <<ENTER_METADATA_ID_OF_SCHEMA_VERSION>>;   

    -- THIS VALUE COMES FROM THE RETURN RESULT OF EXECUTING _CODE.MSSQL_MIGRATE...

    -- ALSO FIND THE VALUE WITH THE FOLLOWING SELECT 
    -- SELECT * FROM _METADATA.MSSQL_SOURCES ORDER BY UPDATED DESC;


    -- YOU SHOULDN'T HAVE TO CHANGE ANY OF THESE VALUES

    SOURCE_DATABASE_NAME STRING DEFAULT CURRENT_DATABASE();

    MSSQL_SOURCE_ID VARCHAR(36);
    RES RESULTSET;
    STMT STRING;

    DDL STRING;

BEGIN
     
    
    SELECT MSSQL_SOURCE_ID INTO :MSSQL_SOURCE_ID
        FROM _METADATA.MSSQL_SOURCES
        WHERE METADATA_ID = :METADATA_ID;


    STMT := 'SELECT REPLACE(X.SCHEMA_DDL,''<<DATABASE_NAME>>'',''' || TARGET_DATABASE_NAME || ''') AS DDL FROM ' || :SOURCE_DATABASE_NAME || '._METADATA.MSSQL_SCHEMAS X WHERE X.MSSQL_SOURCE_ID = ''' || :MSSQL_SOURCE_ID || '''';

    RES := (EXECUTE IMMEDIATE :STMT);

    LET _SCHEMA_CURSOR CURSOR FOR RES;

    FOR _RECORD IN _SCHEMA_CURSOR DO
         
        DDL := _RECORD.DDL;
        EXECUTE IMMEDIATE :DDL;

    END FOR;

    CLOSE _SCHEMA_CURSOR;


    STMT := 'SELECT REPLACE(X.TABLE_DDL,''<<DATABASE_NAME>>'',''' || TARGET_DATABASE_NAME || ''') AS DDL FROM ' || :SOURCE_DATABASE_NAME || '._METADATA.MSSQL_TABLES X WHERE X.MSSQL_SOURCE_ID = ''' || :MSSQL_SOURCE_ID || '''';

    RES := (EXECUTE IMMEDIATE :STMT);

    LET _TABLE_CURSOR CURSOR FOR RES;

    FOR _RECORD IN _TABLE_CURSOR DO
         
        DDL := _RECORD.DDL;
        EXECUTE IMMEDIATE :DDL;

    END FOR;

    CLOSE _TABLE_CURSOR;


    STMT := 'SELECT REPLACE(X.VIEW_DDL,''<<DATABASE_NAME>>'',''' || TARGET_DATABASE_NAME || ''') AS DDL FROM ' || :SOURCE_DATABASE_NAME || '._METADATA.MSSQL_VIEWS X WHERE X.MSSQL_SOURCE_ID = ''' || :MSSQL_SOURCE_ID || '''';

    RES := (EXECUTE IMMEDIATE :STMT);

    LET _VIEW_CURSOR CURSOR FOR RES;

    FOR _RECORD IN _VIEW_CURSOR DO
         
        DDL := _RECORD.DDL;
        EXECUTE IMMEDIATE :DDL;

    END FOR;

    CLOSE _VIEW_CURSOR;


    STMT := 'SELECT REPLACE(X.FOREIGN_KEY_DDL,''<<DATABASE_NAME>>'',''' || TARGET_DATABASE_NAME || ''') AS DDL FROM ' || :SOURCE_DATABASE_NAME || '._METADATA.MSSQL_FOREIGN_KEYS X WHERE X.MSSQL_SOURCE_ID = ''' || :MSSQL_SOURCE_ID || '''';

    RES := (EXECUTE IMMEDIATE :STMT);

    LET _FOREIGN_CURSOR CURSOR FOR RES;

    FOR _RECORD IN _FOREIGN_CURSOR DO
         
        DDL := _RECORD.DDL;
        EXECUTE IMMEDIATE :DDL;

    END FOR;

    CLOSE _FOREIGN_CURSOR;

    RETURN 'SCHEMA OBJECTS CREATED';
      
END;
